# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Utkarsh J
email: jadhav.utkarsh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  WIP! I am currently working towards making this site better! I know it sucks to see WIP
  and not to connect. Meanwhile, I can be reached on 'jadhav<dot>utkarsh<at>gmail<dot>com'. 
  Since JS is fairly new to me, I am trying my hand on NODEJS with Jekyll to build this site. 
  Have any good suggestion? Shoot me a mail! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  utkjad

# Build settings
markdown: kramdown
